spring:
  cache:
    type: redis
    redis:
      key-prefix: "webtoon-catalog::"
      use-key-prefix: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2s
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
