spring:  
  datasource:  
    url: jdbc:postgresql://localhost:5432/webtoon  
    username: webtoon  
    password: webtoon  
  jpa:  
    hibernate:  
      ddl-auto: validate  
    properties:  
      hibernate:  
        format_sql: true  
        jdbc:  
          time_zone: UTC  
    open-in-view: false  
  flyway:  
    enabled: true  
    locations: classpath:db/migration  
  
logging:  
  level:  
    org.springframework.security: INFO  
    org.hibernate.SQL: DEBUG  
    org.hibernate.orm.jdbc.bind: TRACE  
