spring:  
  application:  
    name: webtoon  
  jackson:  
    serialization:  
      WRITE_DATES_AS_TIMESTAMPS: false  
  mvc:  
    problemdetails:  
      enabled: true  
  profiles:  
    default: dev  
  
server:  
  port: 8080  
  
management:  
  endpoints:  
    web:  
      exposure:  
        include: health,info  
  endpoint:  
    health:  
      probes:  
        enabled: true  
